name: Ignore Docs Changes

on:
  push:
    paths-ignore:
      - '*.md'
      - 'docs/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - run: echo "Running because non-docs files changed"
