name: PR Check

on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  pr-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Print branch name
        run: echo "PR check running for branch"
