name: Secrets Demo

on: push

jobs:
  show-secret-status:
    runs-on: ubuntu-latest

    steps:
      - name: Check if secret exists
        run: |
          if [ -n "${{ secrets.FIRST_SECRET }}" ]; then
            echo "The secret is set: true"
          else
            echo "Secret missing"
          fi

      - name: Try printing the secret (for demo)
        run: echo "${{ secrets.FIRST_SECRET }}"
