name: Secrets as Env

on: push

jobs:
  env-secret-demo:
    runs-on: ubuntu-latest

    steps:
      - name: Use secret as env variable
        env:
          SECRET_MESSAGE: ${{ secrets.FIRST_SECRET }}

        run: |
          echo "Using secret safely"
          echo "Length of secret is ${#SECRET_MESSAGE}"
